set(BUILD_INFO_FILE ${CMAKE_BINARY_DIR}/generated/build_info.h)

add_custom_command(
    OUTPUT ${BUILD_INFO_FILE}.generated
    COMMAND ${CMAKE_COMMAND} -E touch ${BUILD_INFO_FILE}
    COMMAND ${CMAKE_COMMAND} -E echo "// auto generated by ${CMAKE_CURRENT_LIST_FILE}" > ${BUILD_INFO_FILE}
    COMMAND ${CMAKE_COMMAND} -E echo "#pragma once" >> ${BUILD_INFO_FILE}
    COMMAND ${CMAKE_COMMAND} -E echo "static const char* BUILD_TIME = __DATE__ \" \" __TIME__;" >> ${BUILD_INFO_FILE}
    COMMENT "Generating build_info.h"
    DEPENDS ${BUILD_INFO_FILE}
    VERBATIM
)

add_custom_target(generate_build_info ALL DEPENDS ${BUILD_INFO_FILE}.generated)
include_directories(${CMAKE_BINARY_DIR}/generated)
