file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/generated)
set(XTILS_AUTOGEN_FILE xtils-autogen.c)
set(XTILS_AUTOGENED ${CMAKE_BINARY_DIR}/generated/${XTILS_AUTOGEN_FILE})

if (NOT XTILS_AUTOGEN_CONTENT)
    message(STATUS "XTILS_AUTOGEN_CONTENT is not defined, using default")
    set(XTILS_AUTOGEN_CONTENT [[
// auto generated by xtils-autogen.cmake
const char* XTILS_BUILD_TIME = __DATE__ " " __TIME__;
]])
endif()


file(WRITE ${XTILS_AUTOGENED}.in "${XTILS_AUTOGEN_CONTENT}")

configure_file(${XTILS_AUTOGENED}.in ${XTILS_AUTOGENED} @ONLY)

add_custom_command(
    OUTPUT ${XTILS_AUTOGENED}.generated
    COMMAND ${CMAKE_COMMAND} -E touch ${XTILS_AUTOGENED}
    COMMENT "Flashing ${XTILS_AUTOGEN_FILE}"
    DEPENDS ${XTILS_AUTOGENED}
    VERBATIM
)
add_library(xtils-autogen STATIC ${XTILS_AUTOGENED})

add_custom_target(generate_xtils_autogen ALL DEPENDS ${XTILS_AUTOGENED}.generated)
include_directories(${CMAKE_BINARY_DIR}/generated)
