set(BUILD_DIR ${CMAKE_BINARY_DIR}/generated)
file(MAKE_DIRECTORY ${BUILD_DIR})

set(BUILD_INFO_FILE ${BUILD_DIR}/build_info.h)

if (NOT DEFINED XTILS_BUILD_INFO_CONTENT)
    message(STATUS "XTILS_BUILD_INFO_CONTENT is not defined, using default")
    set(BUILD_INFO_CONTENT [[
// auto generated by xtils-autogen.cmake
#pragma once
static const char* BUILD_TIME = __DATE__ " " __TIME__;]])
else()
    set(BUILD_INFO_CONTENT ${XTILS_BUILD_INFO_CONTENT})
endif()


file(WRITE ${BUILD_INFO_FILE}.in "${BUILD_INFO_CONTENT}")

configure_file(${BUILD_INFO_FILE}.in ${BUILD_INFO_FILE} @ONLY)
set(BUILD_INFO_FILE ${CMAKE_BINARY_DIR}/generated/build_info.h)

add_custom_command(
    OUTPUT ${BUILD_INFO_FILE}.generated
    COMMAND ${CMAKE_COMMAND} -E touch ${BUILD_INFO_FILE}
    COMMENT "Flashing build_info.h"
    DEPENDS ${BUILD_INFO_FILE}
    VERBATIM
)

add_custom_target(generate_build_info ALL DEPENDS ${BUILD_INFO_FILE}.generated)
include_directories(${CMAKE_BINARY_DIR}/generated)
